// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import Nimbleway from 'nimbleway';

const client = new Nimbleway({
  apiKey: 'My API Key',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('top level methods', () => {
  // Prism tests are disabled
  test.skip('extract: only required params', async () => {
    const responsePromise = client.extract({ url: 'https://example.com/page' });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('extract: required and optional params', async () => {
    const response = await client.extract({
      url: 'https://example.com/page',
      browser: 'chrome',
      city: 'Los Angeles',
      client_timeout: 25000,
      consent_header: true,
      cookies: [
        {
          creation: 'creation',
          domain: 'domain',
          expires: 'string',
          extensions: ['string'],
          hostOnly: true,
          httpOnly: true,
          lastAccessed: 'lastAccessed',
          maxAge: 'Infinity',
          name: 'name',
          path: 'path',
          pathIsDefault: true,
          sameSite: 'strict',
          secure: true,
          value: 'value',
        },
      ],
      country: 'US',
      debug_options: {
        collect_har: true,
        no_retry_mode: true,
        record_screen: true,
        redact: true,
        show_cursor: true,
        solve_captcha: true,
        trace: true,
        upload_engine_logs: true,
        verbose: true,
        with_proxy_usage: true,
      },
      device: 'desktop',
      disable_ip_check: false,
      driver: 'vx8',
      dynamic_parser: { myParser: 'bar' },
      expected_status_codes: [200, 201],
      export_userbrowser: false,
      format: 'json',
      headers: { 'User-Agent': 'CustomBot/1.0', 'Accept-Language': 'en-US' },
      http2: true,
      ip6: false,
      is_xhr: true,
      locale: 'en-US',
      markdown: false,
      metadata: {
        account_name: 'acme-corp',
        definition_id: 456,
        definition_name: 'product-scraper',
        endpoint: '/api/v2/scrape',
        execution_id: 'exec-abc123',
        flowit_task_id: 'task-xyz789',
        input_id: 'input-123',
        pipeline_execution_id: 12345,
        query_template_id: 'template-qry-001',
        source: 'web-app',
        template_id: 789,
        template_name: 'e-commerce-template',
      },
      method: 'GET',
      native_mode: 'requester',
      network_capture: [
        {
          method: 'GET',
          resource_type: 'string',
          status_code: 100,
          url: { value: 'value', type: 'exact' },
          validation: true,
          wait_for_requests_count: 0,
          wait_for_requests_count_timeout: 1,
        },
      ],
      no_html: false,
      no_userbrowser: false,
      os: 'windows',
      parse: true,
      parse_options: { merge_dynamic: true },
      parser: { myParser: 'bar' },
      proxy_provider: 'brightdata',
      proxy_providers: {
        '911proxy': 1,
        always: 1,
        brightdata: 70,
        brightup: 1,
        direct911proxy: 1,
        froxy: 1,
        ipfoxy: 1,
        local: 1,
        'nimble-isp': 1,
        'nimble-isp-mobile': 1,
        oculusproxies: 1,
        oxylabs: 30,
        packetstream: 1,
        proxit: 1,
        proxit_preprod: 1,
        'proxit-linux': 1,
        'proxit-macos': 1,
        'proxit-rental': 1,
        'proxit-windows': 1,
        rayobyte: 1,
        research: 1,
        smartproxy: 1,
        thesocialproxy: 1,
        thesocialproxy2: 1,
      },
      query_template: {
        id: '182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e',
        api_type: 'WEB',
        pagination: { next_page_params: {} },
        params: { foo: 'bar' },
      },
      raw_headers: true,
      referrer_type: 'random',
      render: true,
      render_flow: [{ wait: { delay: 2000 } }, { click: { selector: '#load-more', timeout: 5000 } }],
      render_options: {
        adblock: true,
        blocked_domains: ['ads.example.com', 'tracker.com'],
        browser_engine: 'chrome',
        cache: false,
        connector_type: 'webit-cdp',
        disabled_resources: ['image', 'stylesheet'],
        enable_2captcha: true,
        extensions: ['extension-id-1', 'extension-id-2'],
        fingerprint_id: 'fp-abc123',
        hackium_configuration: {
          collect_logs: true,
          do_not_fix_math_salt: true,
          enable_document_element_spoof: true,
          enable_document_has_focus: true,
          enable_fake_navigation_history: true,
          enable_key_ordering: true,
          enable_sniffer: true,
          enable_verbose_logs: true,
        },
        headless: true,
        include_iframes: true,
        load_local_storage: true,
        local_storage_keys_to_load: ['authToken', 'userId'],
        mouse_strategy: 'linear',
        no_accept_encoding: true,
        override_permissions: true,
        random_header_order: true,
        render_type: 'load',
        store_local_storage: true,
        timeout: 30000,
        typing_interval: 100,
        typing_strategy: 'simple',
        userbrowser: true,
        wait_until: 'networkidle2',
        with_performance_metrics: true,
      },
      request_timeout: 30000,
      return_response_headers_as_header: true,
      save_userbrowser: false,
      session: { id: 'id', prefetch_userbrowser: true, retry: true, timeout: 1 },
      skill: 'dynamic-content',
      skip_ubct: false,
      state: 'CA',
      tag: 'campaign-2024-q1',
      template: { name: 'x', params: {} },
      type: 'generic',
      userbrowser_creation_template_rendered: {
        id: 'id',
        allowed_parameter_names: ['x'],
        render_flow_rendered: [{ foo: {} }],
      },
    });
  });
});
